#!/bin/bash

sysrq_key="sub"  # the SysRq key(s), Sync, Unmount, reBoot
password="$2"
seqno="$(date +%s)"
salt="$(dd bs=12 count=1 if=/dev/urandom 2>/dev/null | openssl enc -base64)"
ip="$1"
req="$sysrq_key,$seqno,$salt"
req="$req,$(echo -n "$req,$ip,$password" | sha1sum | cut -c1-40)"

if ! ping -c 1 -W 1 $ip >/dev/null ; then
  >&2 echo "Host is not up"
  exit 1
fi

echo "$req"|socat stdin udp-sendto:$ip:9
echo "Waiting for $ip to shutdown"
while ping -W 1 -c 1 $ip >/dev/null ; do sleep 1 ; done
echo "Waiting for $ip to restart"
while ! ping -W 1 -c 1 $ip >/dev/null ; do sleep 1 ; done
