name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y make wget xz-utils proot qemu-user-static squashfs-tools

      - name: Build
        run: |
          make -j4

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}

      - name: Upload focal-minimal-cloudimg-arm64-root.tar.xz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: focal-minimal-cloudimg-arm64.tar.xz
          asset_path: dist/focal/minimal.tar.xz
          asset_content_type: application/octet-stream

      - name: Upload k3s-arm64-1.24.tar.xz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: k3s-arm64-1.24.tar.xz
          asset_path: dist/k3s-arm64-1.24.tar.xz
          asset_content_type: application/octet-stream

      - name: Upload kernel
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: vmlinuz
          asset_path: dist/focal/vmlinuz
          asset_content_type: application/octet-stream

      - name: Upload initramfs
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: initrd.img
          asset_path: dist/focal/initrd.img
          asset_content_type: application/octet-stream
